### ISSUE TITLE
Make Graphs to display on client

### ISSUE THREAD

**Issue by leonidscott** [UMM-CSci-3601-S17/digital-display-garden-iteration-3-revolverenguardia#18]
Create the content we want on the admin page

**Comment by leonidscott** [comment]
**TODO** 

- [x] Create graph using actual database data  
- [ ] Test: Correct db data, `makeJSON()`, test everything else.  
- [x] Put graphs on admin  
- [ ] Make Documentation 
- [x] Make email asking what type of content we should provide in graphs.
